In [1]:
import numpy as np

In [2]:
# The column names for this np array ['Apple', 'Beef', 'Eggs', 'Potatoes']
# The row names for this np array ['Carbonhydrates', 'Protien', 'Fat']
a = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]
             ])

In [ ]:
# TODO: Calculate the sum. Which axis should you use? axis=0? axis=1?  

In [8]:
# Print out the total Calories of ['Apple', 'Beef', 'Eggs', 'Potatoes']
print(np.sum(a, axis=0))

[ 59.  239.  155.4  76.9]


In [11]:
# Print out the total Calories of ['Carbonhydrates', 'Protien', 'Fat']
print(np.sum(a, axis=1))
print(np.sum(a, axis=1).reshape((3,1)))

[128.4 165.2 236.7]
[[128.4]
 [165.2]
 [236.7]]


In [13]:
# TODO: Calculate the ingredient percentage of each food!
a0 = np.sum(a, axis=0).reshape(1,4)
a/a0

array([[0.94915254, 0.        , 0.02831403, 0.88426528],
       [0.02033898, 0.43514644, 0.33462033, 0.10403121],
       [0.03050847, 0.56485356, 0.63706564, 0.01170351]])